env: "toto"

# Nexus
# General
nexus_required_libs:
  - unzip
  - openjdk-8-jdk

nexus_mirror: https://download.sonatype.com/nexus/3
nexus_package_name: "{{ (nexus_version == 'latest') | ternary('', 'nexus-') }}{{ nexus_version }}-unix"
nexus_package: "{{ nexus_package_name }}.tar.gz"
nexus_sources_url: "{{ nexus_mirror }}/{{ nexus_package }}"

nexus_version: latest # Or: 3.27.0-03, 3.26.0-04, etc...

## Owner
nexus_user: nexus
nexus_group: nexus

# Service options

## start on boot
nexus_service_enabled: True
# current state: started, stopped
nexus_service_state: started

## Files & Paths
nexus_installation_path: /opt/nexus
nexus_log_path: /var/log/nexus
nexus_data_path: /var/nexus
nexus_tmp_path: "{{ nexus_data_path }}/tmp"

## Port & host
nexus_host: localhost
nexus_port: 8081
nexus_context_path: /

## JMX
nexus_jmx_enabled: false
nexus_jmx_port: 9010
nexus_jmx_remote: "true"
nexus_jmx_local: "false"
nexus_jmx_authenticate: "false"
nexus_jmx_ssl: "false"

nexus_java_xms: 512M
nexus_java_xmx: 512M
nexus_java_xxmaxdirectmemorysize: 1003m
nexus_max_filedescriptors: 65536

# SECURITY
nexus_admin_password: admin123
nexus_anonymous_access: true

# MISCELLANEOUS
nexus_force_reinstall: false



#SOAPUI
soapui_version: 5.5.0
soapui_install_path: /opt/soapui

soapui_url: http://dl.eviware.com/soapuios/{{ soapui_version }}/SoapUI-{{ soapui_version }}-linux-bin.tar.gz
soapui_required_libs:
  - unzip



######JENKINS######
# Optional method of pinning a specific version of Jenkins and/or overriding the


jenkins_version: "2.190"
# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_prefer_lts: false
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8090
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

# Plugin list can use the plugin name, or a name/version dict.
jenkins_plugins: []
#  - blueocean
#  - name: influxdb
#    version: "1.12.1"

jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
jenkins_updates_url: "https://updates.jenkins.io"

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""


#DEBIAN
jenkins_repo_url: deb https://pkg.jenkins.io/debian{{ '-stable' if (jenkins_prefer_lts | bool) else '' }} binary/
jenkins_repo_key_url: https://pkg.jenkins.io/debian{{ '-stable' if (jenkins_prefer_lts | bool) else '' }}/jenkins.io.key
jenkins_pkg_url: https://pkg.jenkins.io/debian/direct
jenkins_init_file: /etc/default/jenkins
jenkins_http_port_param: HTTP_PORT
jenkins_java_options_env_var: JAVA_ARGS




#################################################
################# JBOSS #########################
#################################################
# tmp peut être global par exemple
jboss_artifacts_dl_dest_dir: /tmp

jboss_group: wildfly
jboss_user: wildfly

jboss_version: 16.0.0.Final
jboss_url: https://download.jboss.org/wildfly/{{ jboss_version }}/wildfly-{{ jboss_version }}.tar.gz
jboss_required_libs:
  - unzip
  - openjdk-8-jdk

jboss_default_http_port: 8080
jboss_default_management_port: 9990
